### ISSUE TITLE
[FEAT] 찜 목록 Site Card, CardCounter 컴포넌트 구현

### ISSUE THREAD

**Issue by Yerim1234** [OZ-Coding-School/oz_03_collabo-003-FE#14]
**Background**

의뢰자의 사이트 관리에 있는 Site Card, 이용자의 찜 목록에 있는 Site Card, 공통으로 있는 CardCounter 컴포넌트구현

**TO-DO**

- [x] MyPageImgCard 컴포넌트 UI 구현
- [x] MyPageImgCard 컴포넌트에 들어가는 BtnHeart 토글 버튼 컴포넌트 UI 구현
- [x] MyPageImgCard 컴포넌트의 Container 컴포넌트를 만들지 고려 중 (원래 Page에서 구현하는 게 더 적합해 보이나, 희주님의 사이트 관리와 찜 목록의 Container (ex. gird 3열 등) 가 동일하기 때문에 반응형까지도 동일하게 구현해야 되기에 고려 중)  
- [ ] 찜 기능을 할 수 있게 BtnHeart 컴포넌트 기능 추가 - 전역 관리  고려 중
- [ ] MyPageImgCard 컴포넌트에 Navigate 기능 추가
- [ ] MyPageCardCounter 기능 추가

**기타 사항**

- ~ 8/15 까지 진행 될 예정이며 필요 시 to-do list에 항목 추가 될 예정 (x) 
- 우선 전체적인 UI만 구현하고 기능은 나중에 추가
