### ISSUE TITLE
[FEAT] 사이트 등록 페이지

### ISSUE THREAD

**Issue by Watnu03** [OZ-Coding-School/oz_03_collabo-003-FE#20]
**Background**

- 사이트 등록에 필요한 양식을 작성하는 페이지
- 대표이미지,타이틀,링크,한줄요약포인트 정보 받기
- 상세내용에 대해서 에디터를 이용해서 사용자가 직접 작성해서 글을 게시할수있다
(이미지는 어떻게 처리할껀지 백엔드와 이야기 필요)

**TO-DO**

- [x] 페이지등록에 필요한 입력 Form UI
- [x] 이미지 처리 방식
- [x] 상세정보 (input/이미지추가)

**기타 사항**
- 에디터: https://tiptap.dev/ 추천받음 = 후보1
