### ISSUE TITLE
[FEAT] Nav 및 Footer UI 제작

### ISSUE THREAD

**Issue by Watnu03** [OZ-Coding-School/oz_03_collabo-003-FE#6]
**Background**

- 어떤 기능을 요청할 건 지의 전반적인 내용 ( ex: 프로젝트 초기 세팅 진행 )
- NavBar 제작
- Footer 제작

**TO-DO**

- [x] Nav UI 제작
- [x] Nav - 카테고리 UI 제작
- [x] Footer UI 제작

**기타 사항**
- .
